n=(input('Digite algo:'))
print('É alphanumérico?',n.isalnum())
print('É uma letra?',n.isalpha())
print('É um digito?',n.isdigit())
print('É um decimal?',n.isdecimal())
print('Está todo minúsculo?',n.islower())
print('Está impresso?',n.isprintable())
print('Tem espaço?',n.isspace())
print('É numérico?',n.isnumeric())
print('É um título?',n.istitle())
print('Está todo maiúsculo?',n.isupper())
print('O tipo primitivo é',type(n))